# Generated by Django 2.2.12 on 2021-07-31 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Emisión')),
                ('serie', models.CharField(max_length=150, unique=True, verbose_name='Serie')),
                ('concepto', models.CharField(max_length=150, unique=True, verbose_name='Concepto')),
                ('cedula', models.CharField(max_length=150, unique=True, verbose_name='Cédula')),
                ('codigo', models.CharField(max_length=150, unique=True, verbose_name='Codigo')),
                ('fechavencimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Vencimiento')),
            ],
            options={
                'verbose_name': 'Facturacion',
                'verbose_name_plural': 'Facturacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grouprov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Grouprov',
                'verbose_name_plural': 'Grouprov',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('valor', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Valor en %')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Pago')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('dia', models.IntegerField(blank=True, null=True, verbose_name='Plazos de Pago')),
                ('tiemp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Diferido')),
                ('desc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento %')),
            ],
            options={
                'verbose_name': 'PriceList',
                'verbose_name_plural': 'PriceList',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('Porcentaje', models.IntegerField(default=0, unique=True, verbose_name='Tarifa en %')),
            ],
            options={
                'verbose_name': 'Precios',
                'verbose_name_plural': 'Precios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('stock', models.IntegerField(default=2, verbose_name='Stock')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('standardcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Estándar')),
                ('purchasecost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Compra')),
                ('currentcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Actual')),
                ('datasheet', models.CharField(max_length=250, null=True, verbose_name='Ficha Técnica')),
                ('detail', models.CharField(max_length=250, null=True, verbose_name='Detalle')),
                ('maxstock', models.IntegerField(default=0, verbose_name='Stock Máximo')),
                ('minstock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('codigo', models.CharField(max_length=150, null=True, unique=True, verbose_name='Código')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('ubic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SucursalDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('ubic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ubicación de Destino')),
            ],
            options={
                'verbose_name': 'SucursalDestino',
                'verbose_name_plural': 'SucursalDestino',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Título')),
                ('dias', models.IntegerField(blank=True, null=True, verbose_name='Plazo de Pago')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Diferido')),
                ('descuento', models.IntegerField(blank=True, null=True, verbose_name='Descuento Precio %')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariff',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timelimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Título')),
                ('dias', models.IntegerField(blank=True, null=True, verbose_name='Plazo de Pago')),
                ('tipo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiempo Diferido')),
            ],
            options={
                'verbose_name': 'Timelimit',
                'verbose_name_plural': 'Timelimit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('suc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contacto', models.CharField(max_length=150, verbose_name='Responsable de envio')),
                ('fechaSalida', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Salida ')),
                ('fechaPrevista', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Llegada')),
                ('Operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Operaciones', verbose_name='Tipo de Operacion')),
                ('sucorigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal', verbose_name='Ubicacion de Origen')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('ref', models.CharField(max_length=150, unique=True, verbose_name='Referencia')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Serie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo')),
                ('cant', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('serie', models.IntegerField(blank=True, null=True, verbose_name='Serie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
            ],
            options={
                'verbose_name': 'Scrap',
                'verbose_name_plural': 'Scrap',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 1')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 2')),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalpagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tipo', models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Crédito')], default='credito', max_length=10, verbose_name='Tipo de Pago')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client')),
                ('plazo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.PriceList')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.CharField(choices=[('solicitud', 'Solicitud'), ('aprobada', 'Aprobada'), ('orden', 'Orden'), ('rechazada', 'Rechazada')], default='solicitud', max_length=10, verbose_name='Estado')),
                ('descuento', models.IntegerField(blank=True, default=0, verbose_name='Descuento')),
                ('baseiva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client')),
                ('plazo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Timelimit')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto')),
                ('tipo_pagos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Payment')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('retencionesiva', models.CharField(choices=[('1', 'Ninguno'), ('2', '721 10 % Retención Iva'), ('3', '723 20 % Retención Iva'), ('4', '725 30 % Retención Iva'), ('5', '727 50 % Retención Iva'), ('6', '729 70 % Retención Iva'), ('7', '731 100 % Retención Iva'), ('8', '7 0 % Retención Iva en cero'), ('9', '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='% Ret. IVA Bienes')),
                ('retencionesservices', models.CharField(choices=[('1', 'Ninguno'), ('2', '721 10 % Retención Iva'), ('3', '723 20 % Retención Iva'), ('4', '725 30 % Retención Iva'), ('5', '727 50 % Retención Iva'), ('6', '729 70 % Retención Iva'), ('7', '731 100 % Retención Iva'), ('8', '7 0 % Retención Iva en cero'), ('9', '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='% Ret. IVA Servicios')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Grouprov', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Provider',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal', verbose_name='Sucursal'),
        ),
        migrations.CreateModel(
            name='DetTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Transfer')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalle de Transferencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Purchase')),
            ],
            options={
                'verbose_name': 'Detalle de Purchase',
                'verbose_name_plural': 'Detalle de Purchase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.purchase',),
        ),
    ]
