# Generated by Django 2.2.12 on 2021-08-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_product_imagesub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagesub',
        ),
    ]
