# Generated by Django 2.2.12 on 2021-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210803_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Medida')),
                ('type', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Medida')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'ordering': ['id'],
            },
        ),
    ]
