# Generated by Django 2.2.12 on 2021-07-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_detpurchase_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detpurchase',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalle de Ventas'},
        ),
        migrations.AlterField(
            model_name='detpurchase',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Purchase'),
        ),
    ]
