# Generated by Django 2.2.12 on 2021-08-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_measures'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='prices',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Tarifa en %'),
        ),
        migrations.AlterField(
            model_name='secuences',
            name='secuenceValue',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Secuencia'),
        ),
    ]
