# Generated by Django 2.2.12 on 2021-08-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210803_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(choices=[('Balao', 'Balao'), ('Balzar', 'Balzar'), ('Colimes', 'Colimes'), ('Daule', 'Daule'), ('Duran', 'Duran'), ('El Empalme', 'El Empalme'), ('El Triunfo', 'El triunfo'), ('Guayaquil', 'Guayaquil'), ('Milagro', 'Milagro'), ('Naranjal', 'Naranjal'), ('Naranjito', 'Naranjito'), ('Quevedo', 'Quevedo'), ('Palestina', 'Palestina'), ('Pedro Carbo', 'Pedro Carbo'), ('Playas', 'Playas'), ('Samborondon', 'Samborondon'), ('Yaguachi', 'Yaguachi'), ('Santa Lucia', 'Santa Lucia'), ('Santa Elena', 'Santa Elena')], default='Guayaquil', max_length=10, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['id'],
            },
        ),
    ]
