# Generated by Django 2.2.12 on 2021-08-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
