# Generated by Django 2.2.12 on 2021-07-15 20:51

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20210715_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='state',
            field=django_fsm.FSMField(choices=[('creada', 'creada'), ('aprobada', 'aprobada'), ('publicada', 'publicada'), ('cancelada', 'cancelada')], default='creada', max_length=50, protected=True, verbose_name='Estado'),
        ),
    ]
