# Generated by Django 2.2.12 on 2021-08-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_delete_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.PriceList'),
        ),
    ]
