# Generated by Django 2.2.12 on 2021-07-15 21:17

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_purchase_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='estado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=django_fsm.FSMField(choices=[('inicia', 'inicia'), ('creada', 'creada'), ('aprobada', 'aprobada'), ('publicada', 'publicada'), ('cancelada', 'cancelada')], default='inicia', max_length=50, protected=True, verbose_name='Estado'),
        ),
    ]
