# Generated by Django 2.2.12 on 2021-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20210715_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='estado',
            field=models.CharField(blank=True, default='inicia', max_length=500, null=True, verbose_name='Estado'),
        ),
    ]
