# Generated by Django 2.2.12 on 2021-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20210804_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Crédito')], max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
