# Generated by Django 2.2.12 on 2021-07-16 16:47

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20210715_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='estado',
            field=models.CharField(choices=[('solicitud', 'Solicitud'), ('aprobada', 'Aprobada'), ('orden', 'Orden'), ('rechazada', 'Rechazada')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=django_fsm.FSMField(choices=[('inicia', 'inicia'), ('creada', 'creada'), ('aprobada', 'aprobada'), ('publicada', 'publicada'), ('cancelada', 'cancelada')], default='creada', max_length=50, protected=True, verbose_name='Estado'),
        ),
    ]
