# Generated by Django 2.2.12 on 2021-07-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20210716_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='plazo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.Timelimit'),
            preserve_default=False,
        ),
    ]
