# Generated by Django 2.2.12 on 2021-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20210804_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Crédito')], default='credito', max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
