# Generated by Django 2.2.12 on 2021-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20210804_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito')], default='Crédito', max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
