# Generated by Django 2.2.12 on 2021-07-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20210720_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='plazo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Timelimit'),
            preserve_default=False,
        ),
    ]
