# Generated by Django 2.2.12 on 2021-07-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20210720_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='plazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Timelimit'),
        ),
    ]
