# Generated by Django 2.2.12 on 2021-08-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_sale_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Provider'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito')], max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
