# Generated by Django 2.2.12 on 2021-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_auto_20210720_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='titulo',
            field=models.CharField(max_length=20, null=True, verbose_name='Plazo'),
        ),
    ]
