# Generated by Django 2.2.12 on 2021-08-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_auto_20210804_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocontable', models.CharField(max_length=150, unique=True, verbose_name='Concepto')),
                ('descripcion', models.TextField(max_length=150, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Plan de Cuenta',
                'verbose_name_plural': 'Planes de Cuentas',
                'ordering': ['id'],
            },
        ),
    ]
