# Generated by Django 2.2.12 on 2021-08-04 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_plancuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrecepcion', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Secuencia')),
                ('concepto', models.CharField(max_length=150, unique=True, verbose_name='Concepto')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('codigo', models.CharField(max_length=150, verbose_name='codigo')),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
                ('costos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Tariff')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Provider')),
            ],
            options={
                'verbose_name': 'Recepciones de Compra',
                'verbose_name_plural': 'Recepciones de Compras',
                'ordering': ['id'],
            },
        ),
    ]
