# Generated by Django 2.2.12 on 2021-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_purchase_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo'),
        ),
    ]
