# Generated by Django 2.2.12 on 2021-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_recepcioncompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='estado',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Pedido', 'Pedido'), ('Cancelada', 'Cancelada')], default='Solicitud', max_length=10, verbose_name='Estado'),
        ),
    ]
