# Generated by Django 2.2.12 on 2021-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_sale_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='desc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
