# Generated by Django 2.2.12 on 2021-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_sale_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='totalpagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
