# Generated by Django 2.2.12 on 2021-08-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_detsale_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retenciones', models.CharField(choices=[('1', 'Ninguno'), ('2', '721 10 % Retención Iva'), ('3', '723 20 % Retención Iva'), ('4', '725 30 % Retención Iva'), ('5', '727 50 % Retención Iva'), ('6', '729 70 % Retención Iva'), ('7', '731 100 % Retención Iva'), ('8', '7 0 % Retención Iva en cero'), ('9', '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='Retenciones')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.PlanCuentas')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto')),
            ],
            options={
                'verbose_name': 'Gastos',
                'verbose_name_plural': 'Gastos',
                'ordering': ['id'],
            },
        ),
    ]
