# Generated by Django 2.2.12 on 2021-07-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_sale_totalpagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 1'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 2'),
        ),
    ]
