# Generated by Django 2.2.12 on 2021-08-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secuences',
            name='secuenceValue',
        ),
    ]
