# Generated by Django 2.2.12 on 2021-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_auto_20210721_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelimit',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Título'),
        ),
    ]
