# Generated by Django 2.2.12 on 2021-08-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_remove_secuences_secuencevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medidas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Measures', verbose_name='Medidas'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='type',
            field=models.CharField(max_length=150, unique=True, verbose_name='Descripción Corta'),
        ),
    ]
