# Generated by Django 2.2.12 on 2021-07-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_auto_20210721_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento %'),
        ),
    ]
