# Generated by Django 2.2.12 on 2021-07-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auto_20210722_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contacto', models.CharField(max_length=150, unique=True, verbose_name='Responsable de envio')),
                ('fechaPrevista', models.DateField(verbose_name='Fecha de Arribo de Mercaderia')),
                ('Operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Operaciones', verbose_name='Tipo de Operacion')),
                ('sucorigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal', verbose_name='Ubicacion de Origen')),
            ],
        ),
    ]
