# Generated by Django 2.2.12 on 2021-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auto_20210806_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='concepto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observación'),
        ),
    ]
