# Generated by Django 2.2.12 on 2021-07-23 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_operaciones_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['id'], 'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfer'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='tipo_pagos',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('tarjetac', 'Tarjeta Crédito'), ('tarjetad', 'Tarjeta Débito'), ('Depósito', 'Depósito'), ('Tranferencia', 'Tranferencia')], default='efectivo', max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fechaPrevista',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Arribo de Mercaderia'),
        ),
    ]
