# Generated by Django 2.2.12 on 2021-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_auto_20210806_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Referencia'),
        ),
    ]
