# Generated by Django 2.2.12 on 2021-08-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_transfer_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sucdestino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sucdestino_fixturetables', to='erp.Sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sucorigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucorigen_fixturetables', to='erp.Sucursal'),
        ),
    ]
