# Generated by Django 2.2.12 on 2021-07-23 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_auto_20210723_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Plazos de Pago')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='fechaSalida',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Salida '),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tipo_pagos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Payment'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fechaPrevista',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Llegada'),
        ),
    ]
