# Generated by Django 2.2.12 on 2021-08-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20210806_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuences',
            name='emision',
            field=models.CharField(default=1, max_length=150, verbose_name='Pto. Emisión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secuences',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='No. Actual'),
        ),
        migrations.AlterField(
            model_name='secuences',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='secuences',
            name='suc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal', verbose_name='Local'),
        ),
    ]
