# Generated by Django 2.2.12 on 2021-07-23 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20210723_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tipo de Pago'),
        ),
        migrations.CreateModel(
            name='DetTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Transfer')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalle de Transferencias',
                'ordering': ['id'],
            },
        ),
    ]
