# Generated by Django 2.2.12 on 2021-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_auto_20210806_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuences',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Sucursal'),
        ),
    ]
