# Generated by Django 2.2.12 on 2021-07-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_auto_20210723_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dettransfer',
            old_name='transfer',
            new_name='sale',
        ),
    ]
