# Generated by Django 2.2.12 on 2021-08-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_auto_20210806_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='femision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Secuences'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal'),
        ),
        migrations.AddField(
            model_name='sale',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Vendor'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
    ]
