# Generated by Django 2.2.12 on 2021-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_auto_20210724_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('ubic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ubicación de Destino')),
            ],
            options={
                'verbose_name': 'SucursalDestino',
                'verbose_name_plural': 'SucursalDestino',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='transfer',
            name='Contacto',
            field=models.CharField(max_length=150, verbose_name='Responsable de envio'),
        ),
    ]
