# Generated by Django 2.2.12 on 2021-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_auto_20210724_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('valor', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Valor en %')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['id'],
            },
        ),
    ]
