# Generated by Django 2.2.12 on 2021-08-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_auto_20210806_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='femision',
        ),
    ]
