# Generated by Django 2.2.12 on 2021-07-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_impuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='iva',
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto'),
        ),
    ]
