# Generated by Django 2.2.12 on 2021-08-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_remove_sale_femision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currentcost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchasecost',
        ),
    ]
