# Generated by Django 2.2.12 on 2021-08-06 21:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_auto_20210806_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancieroPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPago', models.CharField(max_length=150, unique=True, verbose_name='Codigo')),
                ('femision', models.DateTimeField(default=datetime.datetime.now)),
                ('fvencimiento', models.DateTimeField(default=datetime.datetime.now)),
                ('concepto', models.CharField(max_length=150, unique=True, verbose_name='Concepto')),
                ('movimiento', models.CharField(choices=[('Protesto Cheque', 'Protesto Cheque'), ('Saldo Inicial Pagos', 'Saldo Inicial Pagos')], default='Saldo Inicial Pagos', max_length=10, verbose_name='Movimiento')),
                ('valorDeuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor Deuda')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Provider')),
            ],
            options={
                'verbose_name': 'Pago Proveedores',
                'verbose_name_plural': 'Pago Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
