# Generated by Django 2.2.12 on 2021-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_auto_20210724_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, verbose_name='Descuento'),
        ),
    ]
