# Generated by Django 2.2.12 on 2021-08-07 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_financieropagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('referencia', models.CharField(max_length=150, unique=True, verbose_name='Referencia')),
                ('concepto', models.CharField(max_length=150, unique=True, verbose_name='Concepto')),
                ('codigo', models.CharField(max_length=150, unique=True, verbose_name='codigo')),
                ('autorizacion', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Autorizacion')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.CharField(choices=[('Anulado', 'Anulado'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado')),
                ('baseiva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantitems', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Provider')),
                ('costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Tariff')),
                ('plazo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Timelimit')),
                ('suscursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto')),
                ('tipo_pagos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Payment')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compra',
                'ordering': ['id'],
            },
        ),
    ]
