# Generated by Django 2.2.12 on 2021-07-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_purchase_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouprov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Provider')),
            ],
            options={
                'verbose_name': 'Grouprov',
                'verbose_name_plural': 'Grouprov',
                'ordering': ['id'],
            },
        ),
    ]
