# Generated by Django 2.2.12 on 2021-08-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_purchaseorderoficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto'),
        ),
    ]
