# Generated by Django 2.2.12 on 2021-07-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_grouprov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelimit',
            name='descuento',
        ),
    ]
