# Generated by Django 2.2.12 on 2021-07-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_remove_timelimit_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.purchase',),
        ),
        migrations.AddField(
            model_name='provider',
            name='retenciones',
            field=models.CharField(choices=[(1, 'Ninguno'), (2, '721 10 % Retención Iva'), (3, '723 20 % Retención Iva'), (4, '725 30 % Retención Iva'), (5, '727 50 % Retención Iva'), (6, '729 70 % Retención Iva'), (7, '731 100 % Retención Iva'), (8, '7 0 % Retención Iva en cero'), (9, '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='Estado'),
        ),
    ]
