# Generated by Django 2.2.12 on 2021-08-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_auto_20210807_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderoficial',
            name='autorizacion',
        ),
        migrations.AddField(
            model_name='compras',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaseorderoficial',
            name='centrocosto',
            field=models.CharField(choices=[('C001 Centro Costo Matriz', 'C001 Centro Costo Matriz'), ('C002 Centro Costo Prosperina', 'C002 Centro Costo Prosperina'), ('C003 Centro Costo Paraiso', 'C003 Centro Costo Paraiso'), ('C004 Centro Costo Santa Lucia', 'C004 Centro Costo Santa Lucia'), ('C005 Centro Costo San Francisco', 'C005 Centro Costo San Francisco'), ('C006 Centro Costo Santa Elena', 'C006 Centro Costo Santa Elena')], default='C001 Centro Costo Matriz', max_length=50, verbose_name='C.Costos'),
        ),
        migrations.AddField(
            model_name='purchaseorderoficial',
            name='descripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_fixturetables', to='erp.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_fixturetables', to='erp.Product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Compras'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Aprobado', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto'),
        ),
        migrations.CreateModel(
            name='detalPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('centrocostos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.PurchaseOrderOficial')),
                ('costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Compras')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto')),
            ],
        ),
    ]
