# Generated by Django 2.2.12 on 2021-08-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_auto_20210807_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto'),
        ),
    ]
