# Generated by Django 2.2.12 on 2021-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_auto_20210728_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='retenciones',
        ),
        migrations.AddField(
            model_name='provider',
            name='retencionesiva',
            field=models.CharField(choices=[(1, 'Ninguno'), (2, '721 10 % Retención Iva'), (3, '723 20 % Retención Iva'), (4, '725 30 % Retención Iva'), (5, '727 50 % Retención Iva'), (6, '729 70 % Retención Iva'), (7, '731 100 % Retención Iva'), (8, '7 0 % Retención Iva en cero'), (9, '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='% Ret. IVA Bienes'),
        ),
        migrations.AddField(
            model_name='provider',
            name='retencionesservices',
            field=models.CharField(choices=[(1, 'Ninguno'), (2, '721 10 % Retención Iva'), (3, '723 20 % Retención Iva'), (4, '725 30 % Retención Iva'), (5, '727 50 % Retención Iva'), (6, '729 70 % Retención Iva'), (7, '731 100 % Retención Iva'), (8, '7 0 % Retención Iva en cero'), (9, '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='% Ret. IVA Servicios'),
        ),
    ]
