# Generated by Django 2.2.12 on 2021-08-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_auto_20210807_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalpurchaseorder',
            name='descripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], default='Cotización', max_length=30, verbose_name='Estado'),
        ),
    ]
