# Generated by Django 2.2.12 on 2021-07-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_auto_20210728_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='costo',
        ),
        migrations.AddField(
            model_name='product',
            name='currentcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Actual'),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.CharField(max_length=250, null=True, verbose_name='Ficha Técnica'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=250, null=True, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='product',
            name='maxstock',
            field=models.IntegerField(default=0, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='product',
            name='minstock',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchasecost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='standardcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Estándar'),
        ),
    ]
