# Generated by Django 2.2.12 on 2021-07-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_auto_20210728_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='baseiva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
