# Generated by Django 2.2.12 on 2021-08-13 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_auto_20210811_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField(default=0)),
                ('estadoSolicitud', models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Enviada', max_length=20, verbose_name='Estado Solicitud')),
                ('referencia', models.CharField(max_length=100, unique=True, verbose_name='Referencia')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DetPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=150, unique=True, verbose_name='Referencia')),
                ('cantidad', models.IntegerField(default=0)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('centrocosto', models.CharField(choices=[('C001 Centro Costo Matriz', 'C001 Centro Costo Matriz'), ('C002 Centro Costo Prosperina', 'C002 Centro Costo Prosperina'), ('C003 Centro Costo Paraiso', 'C003 Centro Costo Paraiso'), ('C004 Centro Costo Santa Lucia', 'C004 Centro Costo Santa Lucia'), ('C005 Centro Costo San Francisco', 'C005 Centro Costo San Francisco'), ('C006 Centro Costo Santa Elena', 'C006 Centro Costo Santa Elena')], default='C001 Centro Costo Matriz', max_length=50, verbose_name='C.Costos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='PedidosCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, unique=True, verbose_name='Referencia')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('concepto', models.CharField(max_length=150, null=True, verbose_name='Concepto')),
                ('estadoSolicitud', models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Enviada', max_length=50, verbose_name='Estado Solicitud')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad')),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalpurchaseorder',
            name='centrocostos',
        ),
        migrations.RemoveField(
            model_name='detalpurchaseorder',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='detalpurchaseorder',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detalpurchaseorder',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='detpurchase',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detpurchase',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tipo_pagos',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ['id'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RenameField(
            model_name='purchaseorderoficial',
            old_name='suscursal',
            new_name='sucursal',
        ),
        migrations.AlterField(
            model_name='compras',
            name='cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Provider'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], default='Solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='detalPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='DetPurchase',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='detpurchaseorder',
            name='costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Compras'),
        ),
        migrations.AddField(
            model_name='detpurchaseorder',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
        ),
        migrations.AddField(
            model_name='detpurchaseorder',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto'),
        ),
        migrations.AddField(
            model_name='detpedido',
            name='costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Compras'),
        ),
        migrations.AddField(
            model_name='detpedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
        ),
    ]
