# Generated by Django 2.2.12 on 2021-07-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_purchase_baseiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprov',
            name='prov',
        ),
        migrations.AddField(
            model_name='provider',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Grouprov', verbose_name='Grupo'),
        ),
    ]
