# Generated by Django 2.2.12 on 2021-08-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_auto_20210813_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='celular',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='client',
            name='correo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='detpedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.PedidosCompra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoscompra',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal'),
        ),
    ]
