# Generated by Django 2.2.12 on 2021-07-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_auto_20210728_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='retencionesiva',
            field=models.CharField(choices=[('1', 'Ninguno'), ('2', '721 10 % Retención Iva'), ('3', '723 20 % Retención Iva'), ('4', '725 30 % Retención Iva'), ('5', '727 50 % Retención Iva'), ('6', '729 70 % Retención Iva'), ('7', '731 100 % Retención Iva'), ('8', '7 0 % Retención Iva en cero'), ('9', '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='% Ret. IVA Bienes'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='retencionesservices',
            field=models.CharField(choices=[('1', 'Ninguno'), ('2', '721 10 % Retención Iva'), ('3', '723 20 % Retención Iva'), ('4', '725 30 % Retención Iva'), ('5', '727 50 % Retención Iva'), ('6', '729 70 % Retención Iva'), ('7', '731 100 % Retención Iva'), ('8', '7 0 % Retención Iva en cero'), ('9', '8 0 % No procede Retención')], default=1, max_length=10, verbose_name='% Ret. IVA Servicios'),
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo')),
                ('cant', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('serie', models.IntegerField(blank=True, null=True, verbose_name='Serie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
            ],
            options={
                'verbose_name': 'Scrap',
                'verbose_name_plural': 'Scrap',
                'ordering': ['id'],
            },
        ),
    ]
