# Generated by Django 2.2.12 on 2021-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_auto_20210817_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='doc',
            field=models.CharField(choices=[('Ruc', 'Ruc'), ('Cédula', 'Cédula'), ('Pasaporte', 'Pasaporte')], default='Cédula', max_length=10, verbose_name='Tipo Documento'),
        ),
    ]
