# Generated by Django 2.2.12 on 2021-07-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_auto_20210728_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Título')),
                ('dias', models.IntegerField(blank=True, null=True, verbose_name='Plazo de Pago')),
                ('tipo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiempo Diferido')),
                ('descuento', models.IntegerField(blank=True, null=True, verbose_name='Descuento Precio')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariff',
                'ordering': ['id'],
            },
        ),
    ]
