# Generated by Django 2.2.12 on 2021-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_client_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito')], default=1, max_length=10, verbose_name='Tipo de Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='doc',
            field=models.CharField(choices=[('Ruc', 'Ruc'), ('Cédula', 'Cédula')], default='Cédula', max_length=10, verbose_name='Tipo Documento'),
        ),
    ]
