# Generated by Django 2.2.12 on 2021-08-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_auto_20210818_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detpedido',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='detpedido',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='detpedido',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pedidoscompra',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='sale',
            name='valdesc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detpedido',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoscompra',
            name='codigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoscompra',
            name='estadoSolicitud',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Enviado', max_length=50, verbose_name='Estado Solicitud'),
        ),
        migrations.AlterField(
            model_name='pedidoscompra',
            name='referencia',
            field=models.CharField(max_length=150, null=True, verbose_name='Referencia'),
        ),
    ]
