# Generated by Django 2.2.12 on 2021-08-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_auto_20210819_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='valdesc',
            new_name='tval',
        ),
    ]
