# Generated by Django 2.2.12 on 2021-07-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_purchase_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='plazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Tariff'),
        ),
    ]
