# Generated by Django 2.2.12 on 2021-08-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_auto_20210819_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoscompra',
            name='codigo',
        ),
    ]
