# Generated by Django 2.2.12 on 2021-08-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_remove_pedidoscompra_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detpedido',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de  Solicitud de Pedido', 'verbose_name_plural': 'Detalle de Solicitud de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedidoscompra',
            options={'ordering': ['id'], 'verbose_name': 'Solicitud de Compra', 'verbose_name_plural': 'Solicitud de Compra'},
        ),
        migrations.RemoveField(
            model_name='detpedido',
            name='referencia',
        ),
    ]
