# Generated by Django 2.2.12 on 2021-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_auto_20210729_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('tiemp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
                ('desc', models.IntegerField(blank=True, null=True, verbose_name='Descuento %')),
                ('dia', models.IntegerField(blank=True, null=True, verbose_name='Plazos de Pago')),
            ],
            options={
                'verbose_name': 'PriceList',
                'verbose_name_plural': 'PriceList',
                'ordering': ['id'],
            },
        ),
    ]
