# Generated by Django 2.2.12 on 2021-08-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_auto_20210819_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detpurchaseorder',
            options={'ordering': ['id'], 'verbose_name': 'Detalle detalle de Ordenes de Compra'},
        ),
        migrations.RenameField(
            model_name='detpurchaseorder',
            old_name='descuento',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='purchaseorderoficial',
            old_name='baseiva',
            new_name='abono',
        ),
        migrations.RenameField(
            model_name='purchaseorderoficial',
            old_name='cantidad',
            new_name='iva',
        ),
        migrations.RenameField(
            model_name='purchaseorderoficial',
            old_name='cantitems',
            new_name='totalpagar',
        ),
        migrations.RenameField(
            model_name='purchaseorderoficial',
            old_name='descuento',
            new_name='tval',
        ),
        migrations.RemoveField(
            model_name='detpurchaseorder',
            name='centrocosto',
        ),
        migrations.RemoveField(
            model_name='detpurchaseorder',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='detpurchaseorder',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='detpurchaseorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderoficial',
            name='centrocosto',
        ),
        migrations.RemoveField(
            model_name='purchaseorderoficial',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='purchaseorderoficial',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='purchaseorderoficial',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='purchaseorderoficial',
            name='tipo_pagos',
        ),
        migrations.AddField(
            model_name='detpurchaseorder',
            name='ordencompra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.PurchaseOrderOficial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderoficial',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito')], default=1, max_length=10, verbose_name='Tipo de Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detpurchaseorder',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pedidoscompra',
            name='estadoSolicitud',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('aprobada', 'Aprobado'), ('asignar Series', 'Asignar Series'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Enviado', max_length=10, verbose_name='Estado Solicitud'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 1'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 2'),
        ),
    ]
