# Generated by Django 2.2.12 on 2021-07-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='tiemp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Diferido'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='plazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.PriceList'),
        ),
    ]
