# Generated by Django 2.2.12 on 2021-08-24 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_auto_20210820_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['id'], 'verbose_name': 'Solicitud de Venta', 'verbose_name_plural': 'Solicitud de Ventas'},
        ),
        migrations.CreateModel(
            name='SaleRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 1')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 2')),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalpagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tipo', models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito')], max_length=10, verbose_name='Tipo de Pago')),
                ('estado', models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], max_length=10, verbose_name='Estado')),
                ('tval', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client')),
                ('plazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.PriceList')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
                ('tax', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Impuesto')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Vendor')),
            ],
            options={
                'verbose_name': 'Pedido de Venta',
                'verbose_name_plural': 'Pedido de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSaleRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('desc', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SaleRequested')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Venta',
                'verbose_name_plural': 'Detalle de Pedido de Ventas',
                'ordering': ['id'],
            },
        ),
    ]
