# Generated by Django 2.2.12 on 2021-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_auto_20210729_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='desc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento %'),
        ),
    ]
