# Generated by Django 2.2.12 on 2021-07-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_auto_20210729_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
