# Generated by Django 2.2.12 on 2021-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_auto_20210824_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detsale',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de solicitud venta', 'verbose_name_plural': 'Detalle de solicitud de Ventas'},
        ),
        migrations.AddField(
            model_name='purchaseorderoficial',
            name='centrocostos',
            field=models.CharField(choices=[('C001 Centro Costo Matriz', 'C001 Centro Costo Matriz'), ('C002 Centro Costo Prosperina', 'C002 Centro Costo Prosperina'), ('C003 Centro Costo Paraiso', 'C003 Centro Costo Paraiso'), ('C004 Centro Costo Santa Lucia', 'C004 Centro Costo Santa Lucia'), ('C005 Centro Costo San Francisco', 'C005 Centro Costo San Francisco'), ('C006 Centro Costo Santa Elena', 'C006 Centro Costo Santa Elena')], default=1, max_length=10, verbose_name='Centro de Costos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='boisfactura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='boispedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('Aprobada', 'Aprobado'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='solicitud', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detpedido',
            name='estadoSolicitud',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('Aprobada', 'Aprobado'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Enviada', max_length=20, verbose_name='Estado Solicitud'),
        ),
        migrations.AlterField(
            model_name='pedidoscompra',
            name='estadoSolicitud',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('Aprobada', 'Aprobado'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Enviado', max_length=10, verbose_name='Estado Solicitud'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito'), ('Cheque', 'Cheque'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Nota  de Credito', 'Nota de Credito')], max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='concepto',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bien', 'Bien'), ('Servicio', 'Servicio')], default='Activo', max_length=10, verbose_name='Concepto orden de Compra'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Por Aprobar', 'Por Aprobar'), ('Aprobada', 'Aprobado'), ('Caducado', 'Caducado'), ('Cerrado', 'Cerrado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Registrado', 'Registrado'), ('Recibido', 'Recibido')], default='Aprobado', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchaseorderoficial',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito'), ('Cheque', 'Cheque'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Nota  de Credito', 'Nota de Credito')], max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito'), ('Cheque', 'Cheque'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Nota  de Credito', 'Nota de Credito')], max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='salerequested',
            name='tipo',
            field=models.CharField(choices=[('Al Contado', 'Al Contado'), ('Crédito', 'Crédito'), ('Cheque', 'Cheque'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Nota  de Credito', 'Nota de Credito')], max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
