# Generated by Django 2.2.12 on 2021-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_auto_20210827_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='boisbandera',
            field=models.BooleanField(default=False),
        ),
    ]
