# Generated by Django 2.2.12 on 2021-07-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_sale_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Código'),
        ),
    ]
