# Generated by Django 2.2.12 on 2021-07-30 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_product_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Crédito')], default='credito', max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(blank=True, max_length=500, null=True, verbose_name='Cantidad')),
                ('ref', models.CharField(max_length=150, unique=True, verbose_name='Referencia')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Serie',
                'ordering': ['id'],
            },
        ),
    ]
