# Generated by Django 2.2.12 on 2021-08-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_sale_boisbandera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('suc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sucursal')),
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashier',
                'ordering': ['id'],
            },
        ),
    ]
