# Generated by Django 2.2.12 on 2021-08-28 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='facturador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Cashier'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fechapago',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='tipofactura',
            field=models.CharField(choices=[('Parcial', 'Parcial'), ('Depósito', 'Depósito')], default=1, max_length=20, verbose_name='Tipo Factura'),
            preserve_default=False,
        ),
    ]
