# Generated by Django 2.2.12 on 2021-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_auto_20210730_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='cant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
