# Generated by Django 2.2.12 on 2021-07-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_auto_20210730_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
