# Generated by Django 2.2.12 on 2021-08-28 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_auto_20210828_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='baseiva',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='femision',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='fregistro',
        ),
        migrations.AddField(
            model_name='compras',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='tipopagofact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Payment'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='sustributario',
            field=models.CharField(choices=[('00 Casos Especiales Cuyo Sustento No Aplica en las Opciones Anteriores', '00 Casos Especiales Cuyo Sustento No Aplica en las Opciones Anteriores'), ('01 Credito Tributario Para Declaraciones De IVA(Servicios y Bienes distintos de Inventarios y Activos Fijos )', '01 Credito Tributario Para Declaraciones De IVA(Servicios y Bienes distintos de Inventarios y Activos Fijos '), ('02 Costo o Gastos Para Declaracion de Ir(Servicios y Bienes Distintos de Inventario y Activos Fijos)', '02 Costo o Gastos Para Declaracion de Ir(Servicios y Bienes Distintos de Inventario y Activos Fijos)'), ('03 Activo Fijo-Credito Tributario para Declaraciones de IVA', '03 Activo Fijo-Credito Tributario para Declaraciones de IVA'), ('04 Activo Fijo-Costo o Gasto para Declaraciones de Ir', '04 Activo Fijo-Costo o Gasto para Declaraciones de Ir'), ('05 Liquidación Gastos De Viaje, Hospedaje Y Alimentación Gastos Ir (A Nombre De Empleados Y No De La Empresa)', '05 Liquidación Gastos De Viaje, Hospedaje Y Alimentación Gastos Ir (A Nombre De Empleados Y No De La Empresa)'), ('06 Inventario - Crédito Tributario Para Declaraciones De IVA', '06 Inventario - Crédito Tributario Para Declaraciones De IVA'), ('07 Inventario - Costos O Gastos Para Declaración De Ir', '07 Inventario - Costos O Gastos Para Declaración De Ir'), ('08 Valor Pagado Para Solicitar Reembolso De Gasto (Intermediario)', '08 Valor Pagado Para Solicitar Reembolso De Gasto (Intermediario)'), ('09 Reembolso Por Siniestros', '09 Reembolso Por Siniestros'), ('10 Distribución De Dividendos, Beneficios, Utilidades', '10 Distribución De Dividendos, Beneficios, Utilidades'), ('11 Convenio De Débito O Recaudación Para Ifis', '11 Convenio De Débito O Recaudación Para Ifis'), ('12 Impuestos Y Retenciones Presuntivos', '12 Impuestos Y Retenciones Presuntivos'), ('13 Valores Reconocidos Por Entidades Del Sector Público A Favor De Sujetos Pasivos', '13 Valores Reconocidos Por Entidades Del Sector Público A Favor De Sujetos Pasivos'), ('14 Valores Facturados Por Socios A Operadoras De Transporte (Que No Constituyen Gastos De Dicha Operadora)', '14 Valores Facturados Por Socios A Operadoras De Transporte (Que No Constituyen Gastos De Dicha Operadora)')], default='00 Casos Especiales Cuyo Sustento No Aplica en las Opciones Anteriores', max_length=10, verbose_name='Tributos'),
        ),
    ]
