# Generated by Django 2.2.12 on 2021-07-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_auto_20210730_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=2, verbose_name='Stock'),
        ),
    ]
