# Generated by Django 2.2.12 on 2021-08-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_auto_20210828_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipofactura',
            field=models.CharField(choices=[('Parcial', 'Parcial'), ('Depósito', 'Depósito')], default='Parcial', max_length=20, verbose_name='Tipo Factura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tipopagofact',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Payment'),
        ),
    ]
