# Generated by Django 2.2.12 on 2021-08-28 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_auto_20210828_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipofactura',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Depósito', 'Depósito')], default='Parcial', max_length=20, verbose_name='Tipo Factura'),
        ),
        migrations.CreateModel(
            name='DetSalePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipofactura', models.CharField(choices=[('Regular', 'Regular'), ('Depósito', 'Depósito')], default='Parcial', max_length=20, verbose_name='Tipo Factura')),
                ('fechapago', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 2')),
                ('facturador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Cashier')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale')),
                ('tipopagofact', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Payment')),
            ],
            options={
                'verbose_name': 'Detalle de pago de Venta',
                'verbose_name_plural': 'Detalle de pago de Venta',
                'ordering': ['id'],
            },
        ),
    ]
