# Generated by Django 2.2.12 on 2021-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_auto_20210828_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='codigo',
        ),
        migrations.AddField(
            model_name='detsalepayment',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], default='Solicitud', max_length=10, verbose_name='Estado'),
        ),
    ]
