# Generated by Django 2.2.12 on 2021-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_auto_20210828_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currentcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Actual'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchasecost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Compra'),
        ),
    ]
