# Generated by Django 2.2.12 on 2021-08-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_remove_product_purchasecost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currentcost',
        ),
    ]
