# Generated by Django 2.2.12 on 2021-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0061_product_currentcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='montodep',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Depósito'),
        ),
    ]
