# Generated by Django 2.2.12 on 2021-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0062_sale_montodep'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsalepayment',
            name='montodep',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Depósito'),
        ),
        migrations.AlterField(
            model_name='detsalepayment',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], default='Facturación Completa', max_length=10, verbose_name='Estado'),
        ),
    ]
