# Generated by Django 2.2.12 on 2021-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0063_auto_20210901_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsalepayment',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], default='Facturar', max_length=10, verbose_name='Estado'),
        ),
    ]
