# Generated by Django 2.2.12 on 2021-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0064_auto_20210902_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsalepayment',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido'), ('A Facturar', 'A Facturar'), ('Facturación Completa', 'Facturación Completa'), ('Cancelada', 'Cancelada')], default='Facturación Completa', max_length=30, verbose_name='Estado'),
        ),
    ]
